import 'server-only';
import type { CountryLaws } from './types';

export const US: CountryLaws = {
  banking: {
    plain_rights: [
      'Under the Electronic Fund Transfer Act, your liability for unauthorized transactions is capped at $50 if you report within 2 business days, or $500 within 60 days.',
      'The CFPB requires banks to investigate billing errors and respond within 30 days (final resolution within 90 days).',
      'Banks must give you 45 days notice before changing account terms.',
      'You can dispute any error on your bank account and the bank must investigate — they cannot close your dispute without written explanation.',
    ],
    plain_obligations: [
      'Banks must acknowledge billing error disputes within 30 days.',
      'Banks must resolve billing error disputes within 90 days.',
      'Banks must provide monthly statements and clearly itemize all fees.',
    ],
    plain_escalation: [
      'File a complaint with the CFPB at consumerfinance.gov/complaint — free, and the bank must respond.',
      'Contact your state Banking Department — they have authority over state-chartered banks.',
      'For national banks (Chase, Bank of America, Wells Fargo), contact the OCC at helpwithmybank.gov.',
    ],
    primary_law: 'Electronic Fund Transfer Act (EFTA) + Fair Credit Billing Act (FCBA)',
    statute_number: '15 U.S.C. § 1693 (EFTA) + 15 U.S.C. § 1666 (FCBA)',
    effective_date: '1978-11-10',
    regulator_name: 'Consumer Financial Protection Bureau (CFPB)',
    regulator_url: 'https://www.consumerfinance.gov',
    regulator_complaint_url: 'https://www.consumerfinance.gov/complaint',
    source_url: 'https://www.consumerfinance.gov/consumer-tools/banking/',
    last_verified: '2026-03-25',
    verification_interval_days: 90,
  },

  telecommunications: {
    plain_rights: [
      'The FCC requires carriers to give you a full bill with all fees — no hidden charges after signup.',
      'You can cancel a new wireless contract within 14 days without an early termination fee (varies by carrier).',
      'Slamming (switching your carrier without consent) is illegal — you are entitled to a full refund.',
      'You can port your number to a new carrier — your old carrier must release it within one business day.',
    ],
    plain_obligations: [
      'Carriers must disclose all material terms before you sign up.',
      'Carriers must process number ports within 1 business day.',
      'Carriers cannot charge you for services you did not authorize (cramming).',
    ],
    plain_escalation: [
      'File an FCC complaint at consumercomplaints.fcc.gov — the carrier must respond within 30 days.',
      'File a complaint with your state Attorney General at naag.org.',
      'For internet service, the FCC\'s informal complaint process is free and effective.',
    ],
    primary_law: 'Communications Act of 1934 + FCC Truth-in-Billing Rules',
    statute_number: '47 U.S.C. § 201 + 47 C.F.R. § 64.2400',
    effective_date: '1934-06-19',
    regulator_name: 'Federal Communications Commission (FCC)',
    regulator_url: 'https://www.fcc.gov',
    regulator_complaint_url: 'https://consumercomplaints.fcc.gov',
    source_url: 'https://www.fcc.gov/consumers/guides/filing-informal-complaint',
    last_verified: '2026-03-25',
    verification_interval_days: 90,
  },

  ecommerce: {
    plain_rights: [
      'Under the FTC Mail Order Rule, online sellers must ship within the stated time (or 30 days if not stated) — otherwise they must offer a full refund.',
      'Credit card chargebacks give you 60 days to dispute unauthorized or undelivered charges.',
      'The FTC prohibits fake reviews and undisclosed paid endorsements.',
      'If an item arrives broken or significantly different from the listing, you are entitled to a full refund under your credit card\'s chargeback rights.',
    ],
    plain_obligations: [
      'Sellers must ship within the advertised timeframe or notify you of delays.',
      'Sellers must provide a full refund if they cannot ship and you cancel.',
      'Sellers must not use fake reviews or deceptive advertising.',
    ],
    plain_escalation: [
      'File an FTC complaint at reportfraud.ftc.gov — used to build enforcement cases.',
      'Dispute the charge with your credit card issuer — strongest and fastest remedy.',
      'File with your state Attorney General for local sellers.',
    ],
    primary_law: 'FTC Mail Order Rule + FTC Act Section 5',
    statute_number: '16 C.F.R. Part 435 + 15 U.S.C. § 45',
    effective_date: '1975-02-02',
    regulator_name: 'Federal Trade Commission (FTC)',
    regulator_url: 'https://www.ftc.gov',
    regulator_complaint_url: 'https://reportfraud.ftc.gov',
    source_url: 'https://www.ftc.gov/business-guidance/resources/consumers-guide-ecommerce',
    last_verified: '2026-03-25',
    verification_interval_days: 90,
  },

  insurance: {
    plain_rights: [
      'Insurers must handle claims in good faith — unreasonable delays or denials can constitute bad faith, which carries extra-contractual damages in most states.',
      'Under the ACA, health insurers cannot deny coverage for pre-existing conditions.',
      'You have the right to an external appeal of a health insurance denial — the independent reviewer\'s decision is binding.',
      'Life and auto insurers must give you a written reason for any denial.',
    ],
    plain_obligations: [
      'Insurers must acknowledge claims within 10 days (varies by state).',
      'Insurers must accept or deny claims within 30–45 days (varies by state).',
      'Insurers must give a written explanation for every denial.',
    ],
    plain_escalation: [
      'File a complaint with your state Insurance Commissioner at naic.org/state-insurance-regulators — binding investigation.',
      'For health insurance denials, request an external appeal through your insurer — free.',
      'Consult a bad faith insurance attorney — many work on contingency.',
    ],
    primary_law: 'State Insurance Codes + ACA (health) + McCarran-Ferguson Act',
    statute_number: '15 U.S.C. § 1011 (McCarran-Ferguson) + 42 U.S.C. § 18001 (ACA)',
    effective_date: '2010-03-23',
    regulator_name: 'State Insurance Commissioner (via NAIC)',
    regulator_url: 'https://www.naic.org',
    regulator_complaint_url: 'https://content.naic.org/consumer',
    source_url: 'https://www.naic.org/state-insurance-regulators.htm',
    last_verified: '2026-03-25',
    verification_interval_days: 90,
  },

  airline: {
    plain_rights: [
      'DOT rules require cash refunds (not vouchers) for canceled or significantly delayed flights.',
      'For domestic flights delayed 3+ hours or international flights delayed 6+ hours due to airline fault, you may be entitled to meals and hotel accommodation.',
      'Airlines must pay up to $1,700 for involuntary bumping on domestic flights (2024 amounts).',
      'Bags delayed more than 12 hours on domestic flights — the airline must refund checked bag fees.',
    ],
    plain_obligations: [
      'Airlines must issue cash refunds within 7 days (credit card) or 20 days (other) for canceled flights.',
      'Airlines must notify passengers of delays and cancellations promptly.',
      'Airlines must not engage in deceptive advertising of fares.',
    ],
    plain_escalation: [
      'File a complaint with DOT at airconsumer.dot.gov — airlines must respond.',
      'Dispute the charge with your credit card for refunds the airline refuses to issue.',
      'Small claims court is effective for claims under your state\'s limit (typically $5,000–$10,000).',
    ],
    primary_law: 'Airline Deregulation Act + DOT Passenger Protections (14 C.F.R. Part 259)',
    statute_number: '14 C.F.R. § 259.5 + 14 C.F.R. § 250',
    effective_date: '2024-10-28',
    regulator_name: 'Department of Transportation (DOT) — Aviation Consumer Protection',
    regulator_url: 'https://www.transportation.gov',
    regulator_complaint_url: 'https://airconsumer.dot.gov/escomplaint/ConsumerForm.cfm',
    source_url: 'https://www.transportation.gov/airconsumer/fly-rights',
    last_verified: '2026-03-25',
    verification_interval_days: 90,
  },

  utilities: {
    plain_rights: [
      'You cannot be disconnected for non-payment without advance written notice (typically 10–30 days, varies by state).',
      'Low-income households qualify for LIHEAP federal assistance for energy bills.',
      'You have the right to dispute any meter reading or bill with your utility.',
      'Utilities must restore service during medical emergencies in most states.',
    ],
    plain_obligations: [
      'Utilities must give advance notice before disconnecting service.',
      'Utilities must offer payment plans for large past-due balances.',
      'Utilities must investigate billing disputes and respond in writing.',
    ],
    plain_escalation: [
      'File a complaint with your state Public Utilities Commission (PUC) — binding.',
      'Contact your state Attorney General\'s consumer protection office.',
      'Apply for LIHEAP energy assistance at liheap.acf.hhs.gov.',
    ],
    primary_law: 'State Public Utility Codes + LIHEAP (42 U.S.C. § 8621)',
    statute_number: '42 U.S.C. § 8621 (LIHEAP)',
    effective_date: '1981-08-13',
    regulator_name: 'State Public Utilities Commission (PUC)',
    regulator_url: 'https://www.naruc.org/about-naruc/about-naruc/',
    regulator_complaint_url: 'https://www.naruc.org/about-naruc/about-naruc/',
    source_url: 'https://www.consumerfinance.gov/consumer-tools/debt-collection/if-you-cant-pay/utility-bills/',
    last_verified: '2026-03-25',
    verification_interval_days: 120,
  },

  transportation: {
    plain_rights: [
      'Ride-hailing companies (Uber, Lyft) must charge the upfront price shown at booking — no surprise surcharges.',
      'Drivers must be licensed and background-checked — you can report unlicensed drivers to the state.',
      'You can dispute any fare directly in the app — platforms must investigate.',
      'The FTC prohibits deceptive surge pricing practices and fake promotions.',
    ],
    plain_obligations: [
      'Platforms must display prices upfront before you confirm.',
      'Platforms must maintain a working dispute resolution process.',
      'Drivers must hold a valid commercial vehicle license where required.',
    ],
    plain_escalation: [
      'File a complaint with the FTC at reportfraud.ftc.gov.',
      'File with your state Attorney General for local ride-hailing issues.',
      'File with your state DMV or Transportation Department for driver conduct.',
    ],
    primary_law: 'FTC Act Section 5 + State Transportation Network Company (TNC) Laws',
    statute_number: '15 U.S.C. § 45',
    effective_date: '1914-09-26',
    regulator_name: 'Federal Trade Commission (FTC) + State Attorney General',
    regulator_url: 'https://www.ftc.gov',
    regulator_complaint_url: 'https://reportfraud.ftc.gov',
    source_url: 'https://www.ftc.gov/business-guidance/blog/2023/06/ftc-takes-action-against-uber',
    last_verified: '2026-03-25',
    verification_interval_days: 120,
  },

  healthcare: {
    plain_rights: [
      'Under the ACA, you cannot be denied health coverage for a pre-existing condition.',
      'You have the right to receive a Good Faith Estimate of costs before non-emergency care (No Surprises Act, 2022).',
      'The No Surprises Act bans surprise medical bills from out-of-network providers at in-network facilities.',
      'You have the right to access your medical records within 30 days and to correct errors.',
    ],
    plain_obligations: [
      'Providers must give a Good Faith Estimate before non-emergency procedures.',
      'Hospitals must post standard charges online.',
      'Insurers cannot impose lifetime limits on essential health benefits.',
    ],
    plain_escalation: [
      'File a No Surprises Act complaint at cms.gov/nosurprises — free dispute resolution.',
      'File with CMS at cms.gov/medicare/complaint for Medicare billing disputes.',
      'For medical malpractice, contact your state Medical Board and consult an attorney.',
    ],
    primary_law: 'Affordable Care Act (ACA) + No Surprises Act (2022)',
    statute_number: '42 U.S.C. § 18001 (ACA) + 29 U.S.C. § 1185e (No Surprises Act)',
    effective_date: '2022-01-01',
    regulator_name: 'Centers for Medicare & Medicaid Services (CMS)',
    regulator_url: 'https://www.cms.gov',
    regulator_complaint_url: 'https://www.cms.gov/nosurprises/consumers',
    source_url: 'https://www.cms.gov/nosurprises',
    last_verified: '2026-03-25',
    verification_interval_days: 90,
  },

  education: {
    plain_rights: [
      'Under the Borrower Defense rule, you can seek federal loan discharge if your school defrauded you.',
      'For-profit schools must meet "gainful employment" standards — failing schools must disclose this.',
      'Title IV schools must have clear refund policies and refund unused financial aid.',
      'Under FERPA, you have the right to access your own academic records.',
    ],
    plain_obligations: [
      'Schools must clearly disclose tuition, fees, and refund policies before enrollment.',
      'Schools must apply for Title IV status and comply with accreditation standards.',
      'Schools must give you a refund of unused tuition if you withdraw within the refund period.',
    ],
    plain_escalation: [
      'File a complaint with the Department of Education at studentaid.gov/feedback-center.',
      'File a Borrower Defense application at studentaid.gov/borrower-defense.',
      'File with your state Higher Education agency or Attorney General.',
    ],
    primary_law: 'Higher Education Act + Borrower Defense Rule (2022)',
    statute_number: '20 U.S.C. § 1087e(h) (Borrower Defense)',
    effective_date: '2022-07-01',
    regulator_name: 'U.S. Department of Education — Federal Student Aid',
    regulator_url: 'https://studentaid.gov',
    regulator_complaint_url: 'https://studentaid.gov/feedback-center',
    source_url: 'https://studentaid.gov/borrower-defense',
    last_verified: '2026-03-25',
    verification_interval_days: 120,
  },

  technology: {
    plain_rights: [
      'California residents have CCPA rights: know what data is collected, delete it, and opt out of sale.',
      'The FTC requires companies to honor their stated privacy policies — violations are enforceable.',
      'Warranty disclaimers cannot waive implied warranties on consumer products (Magnuson-Moss Act).',
      'The FTC\'s new click-to-cancel rule (2025) requires subscriptions to be as easy to cancel as to sign up.',
    ],
    plain_obligations: [
      'Companies must honor the privacy policy published at time of data collection.',
      'Companies must provide a simple way to cancel subscriptions.',
      'Companies must honor express warranties stated at point of sale.',
    ],
    plain_escalation: [
      'File a complaint with the FTC at reportfraud.ftc.gov.',
      'California residents can file with the California Privacy Protection Agency at cppa.ca.gov.',
      'For data breaches, file with the FTC and your state Attorney General.',
    ],
    primary_law: 'FTC Act Section 5 + Magnuson-Moss Warranty Act + California CCPA',
    statute_number: '15 U.S.C. § 45 + 15 U.S.C. § 2301 + Cal. Civ. Code § 1798.100',
    effective_date: '2020-01-01',
    regulator_name: 'Federal Trade Commission (FTC)',
    regulator_url: 'https://www.ftc.gov',
    regulator_complaint_url: 'https://reportfraud.ftc.gov',
    source_url: 'https://www.ftc.gov/tips-advice/business-center/privacy-and-security',
    last_verified: '2026-03-25',
    verification_interval_days: 90,
  },

  retail: {
    plain_rights: [
      'The Magnuson-Moss Warranty Act requires full written warranties to be honored — defective products must be repaired, replaced, or refunded.',
      'Implied warranties (product does what it\'s supposed to do) cannot be disclaimed on consumer goods in many states.',
      'You can dispute credit card charges for defective goods within 60 days of the statement.',
      'Most states have lemon laws for vehicles — typically 3 repair attempts for the same defect triggers a buyback.',
    ],
    plain_obligations: [
      'Sellers must honor advertised prices.',
      'Sellers must honor their stated return and warranty policies.',
      'Sellers cannot use bait-and-switch tactics.',
    ],
    plain_escalation: [
      'File a complaint with the FTC at reportfraud.ftc.gov.',
      'File with your state Attorney General for local retailers.',
      'Use small claims court for amounts under your state\'s limit — quick and inexpensive.',
    ],
    primary_law: 'Magnuson-Moss Warranty Act + FTC Act + State Consumer Protection Laws',
    statute_number: '15 U.S.C. § 2301',
    effective_date: '1975-01-04',
    regulator_name: 'Federal Trade Commission (FTC)',
    regulator_url: 'https://www.ftc.gov',
    regulator_complaint_url: 'https://reportfraud.ftc.gov',
    source_url: 'https://www.ftc.gov/consumer-information/2011/02/consumer-warranty-rights',
    last_verified: '2026-03-25',
    verification_interval_days: 120,
  },

  food_beverage: {
    plain_rights: [
      'The FDA requires food to be safe and accurately labeled — selling contaminated or mislabeled food violates federal law.',
      'You can report foodborne illness to the FDA and CDC — investigations are taken seriously.',
      'Restaurants and food manufacturers must comply with local health codes — violations can be reported to your local health department.',
      'False nutrition claims or misleading labeling can be reported to the FTC and FDA.',
    ],
    plain_obligations: [
      'Food companies must comply with FDA Food Safety Modernization Act (FSMA) standards.',
      'Restaurants must display health inspection scores where required by local law.',
      'Manufacturers must recall unsafe products and notify consumers.',
    ],
    plain_escalation: [
      'Report food safety issues to the FDA at reportaproblem.food.fda.gov.',
      'Report foodborne illness to the CDC at cdc.gov/reportillness.',
      'Contact your local health department for restaurant complaints.',
    ],
    primary_law: 'Food Safety Modernization Act (FSMA) + FD&C Act',
    statute_number: '21 U.S.C. § 301 (FD&C Act) + 21 U.S.C. § 2201 (FSMA)',
    effective_date: '2011-01-04',
    regulator_name: 'Food and Drug Administration (FDA)',
    regulator_url: 'https://www.fda.gov',
    regulator_complaint_url: 'https://www.accessdata.fda.gov/scripts/reportaproblem/',
    source_url: 'https://www.fda.gov/food/recalls-outbreaks-emergencies/how-report-problem-food',
    last_verified: '2026-03-25',
    verification_interval_days: 120,
  },

  government: {
    plain_rights: [
      'Under the Administrative Procedure Act, you can challenge arbitrary or unlawful government decisions in federal court.',
      'The Freedom of Information Act (FOIA) gives you the right to access government records within 20 days.',
      'You have the right to file complaints about federal employees with the relevant Inspector General.',
      'Due process requires notice and an opportunity to be heard before the government deprives you of a significant benefit.',
    ],
    plain_obligations: [
      'Federal agencies must respond to FOIA requests within 20 business days.',
      'Agencies must publish their complaint processes publicly.',
      'Government contractors must follow the Federal Acquisition Regulation (FAR).',
    ],
    plain_escalation: [
      'Contact your Congressional representative\'s constituent services office — they have leverage over agencies.',
      'File a FOIA request at foia.gov.',
      'File a complaint with the relevant Inspector General at ignet.gov.',
    ],
    primary_law: 'Administrative Procedure Act + Freedom of Information Act',
    statute_number: '5 U.S.C. § 551 (APA) + 5 U.S.C. § 552 (FOIA)',
    effective_date: '1966-07-04',
    regulator_name: 'U.S. Office of Inspector General (agency-specific)',
    regulator_url: 'https://www.ignet.gov',
    regulator_complaint_url: 'https://www.ignet.gov/content/inspectors-general-directory',
    source_url: 'https://www.foia.gov',
    last_verified: '2026-03-25',
    verification_interval_days: 180,
  },
};
